sudo: false
dist: trusty
language: cpp

#compiler:
#  - gcc

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-5
      - gfortran-5
      - liblapack-dev

git:
  depth: 1

env:
  global:
    - MAKEFLAGS="-j 20"

before_script:
  

script:
  - cd src
  - rm -r -f ../exe/linux/
  - make clean
  - COMPILER=gcc5 CXX=g++-5 FC=gfortran-5 STATIC=no make -j 20 install
  - cd ..
  - wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda update --yes conda
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - conda install --yes python=$TRAVIS_PYTHON_VERSION pip numpy scipy pandas matplotlib nose
  - pip install git+https://github.com/modflowpy/flopy.git@develop
  - pip install git+https://github.com/jtwhite79/pyemu.git@develop
  - export PYTHONPATH=$PYTHONPATH:.
  - #cd benchmarks
  - export PATH="./test_bin/linux:../test_bin/linux:../../test_bin/linux:$PATH"
  - #nosetests -v -w ./benchmarks travis_tests.py 
  - nosetests -v -w ./benchmarks travis_tests.py
  - nosetests -v -w ./benchmarks ies_test:test_chenoliver
  - nosetests -v -w ./benchmarks opt_test:std_weights_test
  - nosetests -v -w ./benchmarks opt_test:run_supply2_test
  - nosetests -v -w ./benchmarks ies_test:test_freyberg_full_cov_reorder
  - nosetests -v -w ./benchmarks ies_test:test_freyberg_full_cov_reorder_run
  - nosetests -v -w ./benchmarks ies_test:test_freyberg_full_cov
  - nosetests -v -w ./benchmarks ies_test:test_freyberg_ineq
  - nosetests -v -w ./benchmarks ies_test:freyberg_localizer_test3
  - nosetests -v -w ./benchmarks ies_test:tenpar_subset_test
  - nosetests -v -w ./benchmarks ies_test:tenpar_full_cov_test
  - nosetests -v -w ./benchmarks ies_test:tenpar_tight_tol_test
  - nosetests -v -w ./benchmarks ies_test:tenpar_narrow_range_test
  - nosetests -v -w ./benchmarks ies_test:tenpar_fixed_test
  - nosetests -v -w ./benchmarks ies_test:tenpar_fixed_test2
  - nosetests -v -w ./benchmarks ies_test:tenpar_subset_how_test
  - nosetests -v -w ./benchmarks ies_test:tenpar_localizer_test3
  - nosetests -v -w ./benchmarks ies_test:test_chenoliver 

notifications:
  email: true
